nelmio_api_doc:
    documentation:
        info:
            title: Rosance Gateway
            description: Public REST API for Rosance!
            version: 0.0.1
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)