api_token_invalidate:
    path: /api/token/invalidate
    
api_refresh_token:
    path: /api/token/refresh

api_login_check:
    path: /api/login_check
    
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }